version: 2

models:
  - name: fct_rental_activity
    description: >
      Fact model ที่มีหนึ่งแถวต่อหนึ่ง rental_id
    columns:
      - name: rental_id
        tests:
          - not_null
          - unique
      - name: rental_month
        tests:
          - not_null
      - name: store_id
        tests:
          - not_null
      - name: revenue_amount
        tests:
          - not_null
      - name: rental_count
        tests:
          - not_null
  - name: metric_company_monthly
    description: >
      KPI รายเดือนระดับบริษัทในรูป Long Format
    columns:
      - name: metric_month
        tests:
          - not_null
      - name: metric_key
        tests:
          - not_null
          - relationships:
              to: ref('metric_definition')
              field: metric_key
      - name: metric_value
        tests:
          - not_null:
              config:
                where: "metric_key NOT IN ('M004', 'M005')"
  - name: metric_store_monthly
    description: >
      KPI รายเดือนแยกตามสาขาในรูป Long Format
    columns:
      - name: metric_month
        tests:
          - not_null
      - name: store_id
        tests:
          - not_null
      - name: metric_key
        tests:
          - not_null
          - relationships:
              to: ref('metric_definition')
              field: metric_key
      - name: metric_value
        tests:
          - not_null:
              config:
                where: "metric_key NOT IN ('M004', 'M005')"

seeds:
  - name: metric_definition
    description: >
      Catalog กลางสำหรับรหัสและนิยาม KPI
    columns:
      - name: metric_key
        tests:
          - not_null
          - unique
      - name: metric_name
        tests:
          - not_null