select
    sale_id::integer as sale_id,
    invoice_number,
    sale_date::date as sale_date,
    customer_code,
    customer_name,
    gender,
    birth_year::integer as birth_year,
    product_code,
    product_name,
    lower(trim(category)) as category,
    size,
    unit_price::numeric(10, 2) as unit_price,
    quantity::integer as quantity,
    revenue::numeric(12, 2) as revenue,
    store_code,
    store_name,
    province,
    nullif(trim(promo_code), '') as promo_code,
    nullif(trim(promo_desc), '') as promo_desc,
    points_redeemed::integer as points_redeemed
from {{ source('raw', 'coffee_sales') }}
